# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/redpitaya_guide-master/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
# IP: The module: 'system_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/redpitaya_guide-master/tmp/4_frequency_counter/4_frequency_counter.gen/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/redpitaya_guide-master/tmp/4_frequency_counter/4_frequency_counter.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
# IP: The module: 'system_dds_compiler_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/redpitaya_guide-master/tmp/4_frequency_counter/4_frequency_counter.gen/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_dds_compiler_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
